### ISSUE TITLE
Unable to access homepage.

### ISSUE THREAD

**Issue by farhan2106** [tarantx/tarant#25]
# Summary

Unable to access https://www.tarant.io/. I am from Malaysia. Just wondering if the server is offline.

![image](https://user-images.githubusercontent.com/897173/103471297-7ad4ff80-4db9-11eb-9c52-6d589210f095.png)

**Comment by kmruiz** [comment]
Hey, thanks for pinging!

Just realised that the domain was actually wrong, now it's https://tarant.js.org/.

Sorry for the (really) late response!
